### ISSUE TITLE
broken html, css, js (dashboard does not work)

### ISSUE THREAD

**Issue by till** [daptin/daptin#133]
- Are you running a release or master: `daptin/daptin:v0.9.9`
- Issue is about a fresh instance (no data in db) or restart: `no data`

---

Hey 👋🏼  — just trying out daptin as I am looking for a simple (headless) CMS.

I had a few random things, first off the user creation (via web), didn't work, so I created one using the API:

```sh
$ curl -X POST 'https://cms.domain/action/user_account/signup' --data '{"attributes":{"name":"cms","email":"my@email.domain","password":"password123","passwordConfirm":"password123"}}'
[{"ResponseType":"client.notify","Attributes":{"__type":"client.notify","message":"Sign-up successful. Redirecting to sign in","title":"Success","type":"success"}},{"ResponseType":"client.redirect","Attributes":{"__type":"client.redirect","delay":2000,"location":"/auth/signin","window":"self"}}]
```

But when I go to `/auth/signin` the page is empty (in Chrome, Safari and Brave) and there are multiple errors in the console:

![DadaDash 2022-08-20 at 3 58 03 PM](https://user-images.githubusercontent.com/27003/185749641-82d55265-957f-41fc-bff1-5d52af3e47d1.jpg)

This is how I start daptin:

```yaml
version: '3'

services:
  daptin:
    image: daptin/daptin:v0.9.9
    environment:
      - "TZ=UTC"
      - "DAPTIN_RUNTIME=release"
      - "DAPTIN_PORT=:6336"
      - "DAPTIN_DB_CONNECTION_STRING=/var/lib/daptin/daptin.db"
      - "DAPTIN_DB_TYPE=sqlite3"
      - "DAPTIN_LOCAL_STORAGE_PATH=/var/db/daptin"
      - "DAPTIN_LOG_LEVEL=info"
    networks:
      - gwlan
    volumes:
      - daptin-storage:/var/db/daptin
      - daptin-db:/var/lib/daptin

volumes:
  daptin-storage:
  daptin-db:

networks:
  gwlan:
    external: true
```

Hope nothing too outrageous?

I noticed that the source code is odd, it seems to not use any quotes for attributes in HTML. Or rarely? But do you have any other suggestion on what to investigate?

---

Aside from the general dashboard issue, I had another question: when I start daptin and access it, it redirects me to this path `/#/backend` and then shows me something about downloading the binary or connecting to an instance. Not entirely sure.

![DadaDash 2022-08-20 at 4 04 10 PM](https://user-images.githubusercontent.com/27003/185750003-44578536-3661-4a52-b36e-ae491a6a35f0.jpg)

But I can't use the instance I just booted? I tried putting the domain in again, and it said unable to connect. I also tried the local `http://localhost:6336`, but no luck. The options under "Cloud Hosted" are just empty.

There's not a whole lot of documentation on how to actually set this up, or did I miss something? The [instructions](https://daptin.github.io/daptin/setting-up/settingup/) for creating a user are a little wrong (missing `-X POST`) and generally didn't seem to work, e.g. I get no sign-in that asks me to register, instead I get what I posted the screenshot of.

Anyway, thanks for helping. :)
