### ISSUE TITLE
What to do?

### ISSUE THREAD

**Issue by LucaGabi** [daptin/daptin#36]
Hi, 

     What to do after:

docker run -p 8080:8080 daptin/daptin

???

Daptin Process ID: 1 17:15:29.417709 main.go:78: Listening at port: :8080
time="2018-06-26T17:15:29Z" level=info msg="Listening websocket server at ... /live"
Daptin Process ID: 1 17:15:29.440444 debug.go:45: [GIN-debug] GET    /live                     --> github.com/daptin/daptin/server/websockets.(*Server).Listen.f
unc2 (6 handlers)
time="2018-06-26T17:15:29Z" level=info msg="Created handler"

Thanks!

**Comment by artpar** [comment]
Hi Luca,

You can checkout the dashboard in browser by going to localhost:8080 
You can signup on this fresh instance and use that to login and get complete access.

You would want to start using by defining your data model, Eg in YAML, you can make a yml file with the following contents (example if you are making a blogging site):

```yaml
Tables:
- TableName: blog
  Columns:
  - Name: title
    DataType: varchar(500)
    ColumnType: label
  - Name: view_count
    DataType: int(11)
    ColumnType: measurement
- TableName: post
  Columns:
  - Name: title
    DataType: varchar(200)
    ColumnType: label
  - Name: body
    DataType: text
    ColumnType: content
- TableName: comment
  Columns:
  - Name: body
    DataType: text
    ColumnType: content
  - Name: likes_count
    ColumnName: likes_count
    DataType: int(11)
    ColumnType: measurement
Relations:
- Subject: comment
  Relation: belongs_to
  Object: post
- Subject: post
  Relation: belongs_to
  Object: blog
- Subject: blog
  Relation: has_one
  Object: post
  ObjectName: current_post
SubjectName: current_post_of
```

Upload this file from the admin dashboard (you can use json too). Please find more examples here at: https://github.com/daptin/market for the various things you can define in YAML files.

Once you upload this schema, daptin will create all the tables in the database and expose the API's.

Now you can begin using these new endpoints to create/read/write/update data. The JSON api follow jsonapi.org  specs and you can use any client available at http://jsonapi.org/implementations/. You can also use the admin dashboard to manually create/import data and more users.

A graphql interface will be available at localhost:8080/graphql 

A few thing:
1. Remember to "Become Administrator" so that signup/sign-in is turned off for guests (dont logout after this before enabling sign-in)
2. Enable sign-in for guests 
  2.1 In the left panel: `Administration` -> `All tables`
  2.2 Look for `user` table, click the pencil icon to edit it
  2.3 Under the `Permission` heading, click `Guests` and Check the `Execute` permission
  2.4 Click Submit to save


Once daptin has exposed your APIs you can create users/usergroups to give read/write permission or you can expose it publicly without any auth as well.

You can find [documentation here](http://docs.dapt.in/). I would love feedback on both the software and the documentation if something doesn't make sense. 

I have written up two walk thrus covering some more basics and advance features, you can read them here:

- [Creating a todo list backend with persistence ](https://hackernoon.com/creating-a-todolist-backend-with-persistence-a1e8d7d39f62)
- [Exposing a static site using oauth2 and gdrive](https://medium.com/@012parth/daptin-walk-through-oauth2-google-drive-subsites-and-grapejs-a6de27d9658a)
